version: '3.8'

services:
  db:
    image: postgres:16
    container_name: favoritefilms-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: favoritefilms-api
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
